import { chromium } from 'playwright';
const OUT='/tmp/claude-0/-home-user-LUXA/1cce5c21-fb76-56ae-8d3e-37fb3f832877/scratchpad/shots4';
import fs from 'node:fs'; fs.mkdirSync(OUT,{recursive:true});
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome',args:['--no-sandbox']});
const ctx=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});
const p=await ctx.newPage(); const errs=[];
p.on('pageerror',e=>errs.push(e.message));
p.on('console',m=>{if(m.type()==='error')errs.push(m.text());});
await p.goto('http://localhost:4180/',{waitUntil:'load'});
await p.waitForTimeout(1200);
console.log('dir:', await p.evaluate(()=>document.documentElement.dir));
console.log('serif applied:', await p.evaluate(()=>getComputedStyle(document.querySelector('.intro__title')).fontFamily));
console.log('font loaded:', await p.evaluate(()=>document.fonts.check("500 24px 'Frank Ruhl Libre'")));
await p.screenshot({path:`${OUT}/pv-start.png`});
const H=await p.evaluate(()=>document.body.scrollHeight);
await p.evaluate(v=>window.scrollTo(0,v),H);
await p.waitForTimeout(1400);
await p.screenshot({path:`${OUT}/pv-invite.png`});
console.log('errors:',errs.length?errs:'none');
await b.close();
